<?php

/*
 * @author paul.huntsberger@gmail.com
 * @file addthis.module
 */

define('ADDTHIS_MODULE_PATH', drupal_get_path('module', 'addthis'));
define('ADDTHIS_PUBID', variable_get('addthis_pubid', null));
define('ADDTHIS_ASYNC', variable_get('addthis_async', null));

/**
 * Implements Hook Menu
 */
function addthis_menu() {
  $items = array();
  //Admin Page
  $items['admin/config/services/addthis'] = array(
    'title' => 'Add This',
    'description' => 'A simple module that allows you to add the "Add This" scripts to your site.',
    'page callback' => 'addthis_admin',
    'access arguments' => array('administer content types'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/addthis.admin.inc',
  );
  return $items;
}

/**
 * Implements Hook Theme
 */
function addthis_theme() {
  $theme = array(
    //Widget.
    'addthis_widget' => array(
      'template' => 'templates/addthis.widget',
      'addthis' => array(
        'classes' => 'addthis_toolbox addthis_default_style addthis_32x32_style',
        //explode buttons, by space.
        'buttons' => 'addthis_button_preferred_1 addthis_button_preferred_2 addthis_button_preferred_3 addthis_button_preferred_4',
      ),
    ),
    //Admin Form.
    'addthis_admin_form' => array(
      'render element' => 'form',
      'template' => 'templates/form.admin',
    )
  );
  return $theme;
}

/**
 * Implements hook_library
 */
function addthis_library() {
  $libraries = array();
  //Normal Widget.
  $libraries['addthis_widget'] = array(
    'title' => 'Add This',
    'website' => 'http://www.addthis.com',
    'version' => '1.0',
    'js' => array(
      //Add This main script
      '//s7.addthis.com/js/300/addthis_widget.js#pubid=' . ADDTHIS_PUBID => array(
        'scope' => 'footer',
        'weight' => -20,
        'group' => JS_LIBRARY,
        'type' => 'external'
      ),
    ),
  );
  //Add this async widget.
  $libraries['addthis_widget_async'] = array(
    'title' => 'Add This Async',
    'website' => 'http://www.addthis.com',
    'version' => '1.0',
    'js' => array(
      //Add this config.
      array(
        'scope' => 'footer',
        'weight' => -21,
        'group' => JS_LIBRARY,
        'type' => 'inline',
        'data' => 'var addthis_config = addthis_config || {};',
      ),
      //Add This main script
      '//s7.addthis.com/js/300/addthis_widget.js#async=1' => array(
        'scope' => 'footer',
        'weight' => -20,
        'group' => JS_LIBRARY,
        'type' => 'external'
      ),
    ),
  );
  //When adding the template, add the main script, as on it's own it needs the async.
  $libraries['addthis_widget_main'] = array(
    'title' => 'Add This Main (Force Async)',
    'website' => 'http://www.addthis.com',
    'version' => '1.0',
    'js' => array(
      //Add The social links builder.
      ADDTHIS_MODULE_PATH . '/js/addthis-main.js' => array(
        'scope' => 'footer',
        'weight' => -19,
        'group' => JS_DEFAULT,
      ),
      'dependencies' => array(
        array('addthis_widget_async'),
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook preprocess
 *  We implicitely remove admin and user sections from add this.
 * @param type $variables
 */
function addthis_preprocess(&$variables) {
  $path = drupal_get_path_alias();
  $paths = array('admin*', 'user*');
  $disallowed = variable_get('addthis_disallowed', null);
  if (!empty($disallowed)) {
    $disallowed = explode("\n", $disallowed);
    foreach ($disallowed as $value) {
      $paths[] = $value;
    }
  }
  $patterns = implode("\n", $paths);
  if (!drupal_match_path($path, $patterns)) {
    $async = ADDTHIS_ASYNC;
    if (!empty($async)) {
      drupal_add_js(array('addThis' => array('pubId' => ADDTHIS_PUBID)), 'setting');
      drupal_add_library('addthis', 'addthis_widget_async');
    } else {
      drupal_add_library('addthis', 'addthis_widget');
    }
  }
}

/**
 * Preprocess Add This Widget
 */
function addthis_preprocess_addthis_widget(&$variables) {
  //Look for the widget and buttons, and explode them into an array.
  if (isset($variables['addthis']) && !empty($variables['addthis']['buttons'])) {
    //Add the Main Library.
    $extras = array();
    //@TODO - this may have to be validated.
    if (!empty($variables['addthis']['image_include'])) {
      $extras['image_include'] = $variables['addthis']['image_include'];
    }
    if (!empty($variables['addthis']['image_exclude'])) {
      $extras['image_exclude'] = $variables['addthis']['image_exclude'];
    }
    if (!empty($variables['addthis']['image_container'])) {
      $extras['image_container'] = $variables['addthis']['image_container'];
    }
    if (!empty($extras)) {
      drupal_add_js(array('addThis' => $extras), 'setting');
    }
    drupal_add_library('addthis', 'addthis_widget_main');
    //Make the buttons into an array we can process with the template.
    $variables['addthis']['buttons'] = explode(' ', $variables['addthis']['buttons']);
  }
}

/**
 * Implements hook_views_api().
 */
function addthis_views_api() {
  return array(
    'api' => 3,
    'path' => ADDTHIS_MODULE_PATH . '/views',
  );
}
